version: "3"
services:

  web:
    build: 
      context: .
      dockerfile: ./web/build/Dockerfile
    container_name: news_recommend_system_web

    volumes:
      - ./web:/webuser/web
    ports:
      - "3031:3031"
      - "8080:8080"
    environment:
      TZ: "Asia/Tokyo"
      LANG: "ja_JP.UTF-8"
    working_dir: /webuser/web
    command: bash -c "/bin/start.sh"

  nginx:
    build:
      context: .
      dockerfile: ./nginx/build/Dockerfile
    container_name: news_recommend_system_nginx

    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log:/var/log/nginx/
    links:
      - web
    ports:
      - "80:80"
    environment:
      TZ: "Asia/Tokyo"
      LANG: "ja_JP.UTF-8"
      BASIC_AUTH_USER_NAME: "root"
      BASIC_AUTH_PASSWD: "eq967yD5"
    command: bash -c "/bin/basic_auth_setup.sh && nginx -c /etc/nginx/nginx.conf"

  classification:
    build:
      context: .
      dockerfile: ./classification/build/Dockerfile
    container_name: news_recommend_system_classification
    environment:
      TZ: "Asia/Tokyo"
      LANG: "ja_JP.UTF-8"

    volumes:
      - ./classification:/root/classification
    working_dir: /root/classification
    restart: always
    command: bash -c "python3 /root/classification/scripts/flask-server.py" 

  db:
    image: mysql:5.7
    container_name: news_recommend_system_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: eq967yD5
      BIND-ADDRESS: 0.0.0.0
      TZ: 'Asia/Tokyo'
      
    volumes:
      - ./db/data/data:/var/lib/mysql
      - ./db/data/log:/var/log/mysql
      
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/initdb.d:/docker-entrypoint-initdb.d
      
    ports:
      - 3306:3306

  scrape:
    build:
      context: .
      dockerfile: ./scrape/build/Dockerfile
    container_name: news_recommend_system_scrape
    environment:
      TZ: "Asia/Tokyo"
    volumes:
      - ./scrape:/root/scrape
    working_dir: /root/scrape
    tty: true
    #command: bash -c "/bin/start.sh" 
    command: bash -c "cron -f" 

